### ISSUE TITLE
examples of Parse pointer and relation fields

### ISSUE THREAD

**Issue by ejwill** [giorgiofellipe/ionic-angular-parse-boilerplate#1]
Adding examples for getting data from pointer and relation fields form Parse would be nice.  Nice boilerplate by the way.

**Comment by giorgiofellipe** [comment]
Will be done asap.
Thank you!

**Comment by giorgiofellipe** [comment]
@ejwill it was done on commit 7913aa56df2b614bbf0657319ca2b32300ac683f
check it out!

**Comment by ejwill** [comment]
looks good :+1: .  all you need now is user login and push notifications and I think you would have every parse service haha :)

**Comment by giorgiofellipe** [comment]
I'll add your suggestions to a list of future features. 
But I'm busy atm, feel free to fork, implement some and send a PR if you want!

Thank you! ;)
